### ISSUE TITLE
website: index, indexMerged, and indexSynthetic have broken html

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#96] opened 2020-05-17 00:10 UTC
I don't know if this is a `pkgdown` bug or something we are doing that we shouldn't, but I noticed that the website [reference for the `index*` data sets](https://argocanada.github.io/argoFloats/reference/index-topic.html) has messed up html for the `<-` character. It seems to be something because of the `\preformatted{}` block:

![image](https://user-images.githubusercontent.com/233584/82132753-9dc68b00-97b9-11ea-9ec0-a753c9b82bbb.png)

```r
#' A sample index of profiles
#'
#' This is created by subsetting a global index to the 1788 Argo profiles
#' that were within a 200km radius of Marsh Harbour, Abaco Island,
#' Bahamas, as of 2020 March 14, using
#' the following code.
#'\preformatted{
#  library(argoFloats)
#' indexAll <- getIndex()
#' index <- subset(indexAll,
#'     circle=list(longitude=-77.06, latitude=26.54, radius=200))
#'}
```

**Comment by dankelley** [comment] 2020-05-17 09:03
Thanks.  I'll look into this.  I noticed when I was updating some things that the triple-backtick scheme does not work.  But there must be a way!

**Comment by dankelley** [comment] 2020-05-17 10:23
I think it's a pkgdown bug.  As the snapshot shows, the code ("develop" as of commit 4fac3b5949507cc650ae3d0069c8716684073e54) now tries both methods that I know of.  It fails in both cases, but is okay within R, in both.

I have not done any websearches to see if this is a known bug in pkgdown.

<img width="906" alt="Screen Shot 2020-05-17 at 7 18 16 AM" src="https://user-images.githubusercontent.com/99469/82141916-08ee7c80-980f-11ea-9562-78d8221a91eb.png">

**Comment by dankelley** [comment] 2020-05-17 10:36
I submitted a bug report at https://github.com/r-lib/pkgdown/issues/1325

**Comment by dankelley** [comment] 2020-05-17 11:25
This is solved by updating `pkgdown` from its github site, using
```R
devtools::install_github("r-lib/pkgdown")
```
So, @richardsc and @j-harbin, please do as above to update your copy of `pkgdown`.

Since inspection of e.g. https://argocanada.github.io/argoFloats/reference/index-topic.html shows clearly that the problem is now solved, and to save time, I am closing this issue to save @richardsc the effort.

**Closed by dankelley** 2020-05-17 11:25 UTC
Labels: website
