### ISSUE TITLE
Question about using the oce package with argoFloats objects

### ISSUE THREAD

**Issue by anna-schrecengost** [ArgoCanada/argoFloats#313] opened 2020-12-02 19:55 UTC
Hello! I am utilizing your amazing R package for a project in my physical oceanography course and I have a question about using the oce package with argo data downloaded with getIndex(). I would like to be able to make hydrographic sections with the data, and have found one way to do so is to use the oce function as.section() on the argo data. However, after subsetting the index and obtaining and reading the profiles with getProfiles() and readProfiles(), as.section() cannot read the resulting file. I also can't force it into an oce object with as.oce(). Is there a way to be able to use this oce function with data obtained with getIndex()?

**Comment by richardsc** [comment] 2020-12-02 20:25
Hi @anna-schrecengost ,

I'm happy that you've found the package, and are finding it useful so far. I have to admit that you are pushing the envelope as far as our development goes, which is great because as more people start to use it we'll have more ideas about what should (and maybe shouldn't) be in it.

To start, can you provide a reproducible example of code showing what you've tried? In other words, some code that we can run to reproduce the error with exactly the same data you've tried to use. That helps us because then we don't get caught up trying to compare apples with oranges.

**Comment by anna-schrecengost** [comment] 2020-12-02 23:28
Of course, sorry about that!

`indexAllmerged <- getIndex(filename="synthetic", destdir = "data/argo")`
`index6901654 <- subset(indexAllmerged, ID=6901654)`
`profiles6901564 <- getProfiles(index6901654)`
`argos6901564 <- readProfiles(profiles6901564)`
`argosClean6901564 <- applyQC(argos6901564)`
`argo.section6901564 <- argosClean6901564%>%as.section()`

Error in as.section(.) : object 'argosClean6901564' not found

**Comment by j-harbin** [comment] 2020-12-03 11:55
Hi @anna-schrecengost,

Thanks for the great question and highlighting some potential future development needed for our package.

In your particular example,

You could do the following code:

```R
library(argoFloats)
library(oce)
indexAllmerged <- getIndex(filename="synthetic", destdir = "data/argo")
index6901654 <- subset(indexAllmerged, ID=6901654)
profiles6901564 <- getProfiles(index6901654)
argos6901564 <- readProfiles(profiles6901564)
argosClean6901564 <- applyQC(argos6901564)
ctd <- lapply(argosClean6901564[["argos"]], as.ctd)
section <- as.section(ctd)
plot(section)
```

In this case, all I have done is took each individual `argos` object within `argosClean6901564` and converted it to a `ctd` object using `ctd <- lapply(argosClean6901564[[“argos”]], as.ctd)`. I took these resulting `ctd` objects and converted them to `section` objects by doing `section <- as.section(ctd)`

One other thing that is worth noting is due to the fact that, as I’m sure you are now aware, 418 profiles takes a while to read, you could also do the following:

```R
library(argoFloats)
library(oce)
if (!exists("argos6901564")) {
indexAllmerged <- getIndex(filename="synthetic", destdir = "data/argo")
index6901654 <- subset(indexAllmerged, ID=6901654)
profiles6901564 <- getProfiles(index6901654)
argos6901564 <- readProfiles(profiles6901564)
}
argosClean6901564 <- applyQC(argos6901564)
ctd <- lapply(argosClean6901564[["argos"]], as.ctd)
section <- as.section(ctd)
plot(section)
```
Which caches and data, and "tells" R to only read the files if it is not already existing. This will save a lot of time in the future!

I hope this helps! Please don’t hesitate to reach out with any further questions.

**Comment by dankelley** [comment] 2020-12-03 12:40
@anna-schrecengost you will want to think about how to plot the sections, e.g. what to put on the x axis.  The default x axis on section-type plots will not be too useful for argo data, because the coordinate is distance from first profile.  (Distance is handy for ship tracks.). I would suggest e.g.
```R
plot(section,xtype="latitude",ztype="image",showBottom=FALSE)
```
(result for J's code shown at bottom).  Note that I am turning off the bottom plotting because the polygon is not filling to the bottom of the panel (in what I consider a bug ... but I won't fix it for a while because this is a busy teaching time).

PS. if you're like me, you'll want to do lots of experiments with plots.  I very often do as follows, so I can keep a session open and rerun my code, without having to wait a long time for slow steps.  Then, if you want to change those first steps, just delete the `.rda` file and rerun the modified code.  Another advantage of this is that you'll have *precisely* reproducible code, which is handy for writing papers and theses.  It is no fun to find, the day before you defend a thesis, that the original source data have changed.  And original argo data *do* change,  Files that once existed on the servers will change names every so often.  And of course, new files are added all the time, so a spatial subset done on Monday may very well be changed on Tuesday.  For operational modelling, this is a good thing (the model always has the latest data) but for many other purposes it can be a pain.  If a reviewer asks for a colour change on a figure and the positions of the data points change, well then it is not really the original paper anymore and the reviewer might just ask for another month or two to start over from the beginning to see if the conclusions still make sense.

I very often save data locally in an `.rda` file, and use a block like
```R
if (file.exists("mydata.rda")) {
   load("mydata.rda")
} else {
   # read in the data, and perhaps do some preliminary processing
   save(MY_DATA, file="mydata.rda")
}
# work with the data, e.g. fiddling with plot details
```

**Comment by dankelley** [comment] 2020-12-03 12:44
Sorry, I forgot to attache the picture... note the blip at 40S, which I think is from the easterly data.  This is why I do not quite like the idea of interpreting the trace of an argo float as a section.

<img width="699" alt="Screen Shot 2020-12-03 at 8 32 47 AM" src="https://user-images.githubusercontent.com/99469/101019378-444e5f80-3543-11eb-9f93-ef5702f29eec.png">

So, I tried with time as the x type
```R
plot(section,xtype="time",ztype="image",showBottom=FALSE)
```
and this makes me think that my guess about the 'blip' was right.  But, really, is a section a smart way to look at data that are not on anything like a line or a simple curve?  That's in the eye of the coder :-)

<img width="699" alt="Screen Shot 2020-12-03 at 8 43 29 AM" src="https://user-images.githubusercontent.com/99469/101019653-aa3ae700-3543-11eb-8233-2cd63fe58128.png">

**Comment by richardsc** [comment] 2020-12-03 15:54
I would just point out from @dankelley's discussion that the "time" type section plot is extremely common in the Argo world, as it shows at least a Lagrangian view of the water properties that a given float sampled. Basically all the Argo float websites use that for their diagnostic-type plots.

What's nice about a `section` object is that you can also use other `oce` plotting functions, e.g. `plotTS()`. Or, you can dive into the individual stations as `ctd` plots, and also easily extract other fields to use.

**Comment by dankelley** [comment] 2020-12-03 16:13
Good points, Clark!

**Comment by anna-schrecengost** [comment] 2020-12-03 20:15
Hi @richardsc, @j-harbin, and @dankelley - thank you so much for your responses! This is really helpful, especially as someone who is completely new to physical oceanography :) I agree that having the data as a `section` object is really useful

**Comment by j-harbin** [comment] 2020-12-04 14:14
@anna-schrecengost ,

If you feel this issue has been addressed please feel free to close it. If not, please add a comment explaining what remains to be done. Additionally, we plan to add more information about Argo and sections to our vignette. If you would like to collaborate in doing so, please let me know :)

**Closed** 2020-12-04 15:38 UTC
