### ISSUE TITLE
showQCTests producing an error

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#529] opened 2021-11-01 17:12 UTC
See `reprex` below:

``` r
library(argoFloats)
ai <- getIndex()
index1 <- subset(ai, ID="6900388")
#> Kept 223 cycles (0.0088%)
profiles <- getProfiles(index1)
argos <- readProfiles(profiles)
#> Warning in readProfiles(profiles): Of 223 profiles read, 1 has >10% of pressure values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     14
showQCTests(argos[[1]])
#> Error in rep("0", nchar(perf) - nchar(fail)): invalid 'times' argument
```

<sup>Created on 2021-11-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I'll take a look at this right now and will let you know if I run into problems.

**Comment by j-harbin** [comment] 2021-11-02 12:02
@dankelley, when I look in the code for qc.R, above the line that causes the error has a message "  ## Add zeros on left of 'fail', if needed to match length of 'perf'". I'll admit hexadecimal "stuff" is not my time to shine. Any ideas how to proceed with this?

**Comment by j-harbin** [comment] 2021-11-02 16:31
I'm adding this comment for myself as I am narrowing in on the issue. The problem is that in some cases `historyAction` does not have QCF$ (or failed tests). When it does have the QCF$ it works fine. See below

``` r
library(argoFloats)
ai <- getIndex()
index1 <- subset(ai, ID="6900388")
#> Kept 223 cycles (0.0088%)
profiles <- getProfiles(index1)
argos <- readProfiles(profiles)
#> Warning in readProfiles(profiles): Of 223 profiles read, 1 has >10% of pressure values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     14
argos[[1]][['historyAction']] # Without QCF$
#>      [,1]   [,2]   [,3] [,4]
#> [1,] "QCP$" "QCP$" "IP" "IP"
argos[[221]][['historyAction']] # With QCF$
#>      [,1]   [,2]   [,3]
#> [1,] "QCP$" "QCF$" "IP"
showQCTests(argos[[221]])
#> Tests performed: 4 5 6 10 14 18 19 21 22 NA NA NA NA NA NA NA NA NA NA NA NA
#>      Failed test  1 (Platform Identification test)
#>      Failed test  4 (Position on Land test)
#>      Failed test  8 (Pressure Increasing test)
#>      Failed test 10 (Top and Bottom Spike test (obsolete))
showQCTests(argos[[1]])
#> Error in rep("0", nchar(perf) - nchar(fail)): invalid 'times' argument
```

<sup>Created on 2021-11-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by j-harbin** [comment] 2021-11-04 11:25
In commit 6c31d9c5e6c484b89f97ee02480d9bb731ac7793 of develop, I've created an warning message when the length of QCP$ (performed) or QCF$ (failed) is greater than one in `historyAction`. See reprex below.

``` r
library(argoFloats)
ai <- getIndex()
index1 <- subset(ai, ID="6900388")
#> Kept 223 cycles (0.00879%)
profiles <- getProfiles(index1)
argos <- readProfiles(profiles)
#> Warning in readProfiles(profiles): Of 223 profiles read, 1 has >10% of pressure values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     14
showQCTests(argos[[1]])
#> Warning: historyAction is not in the expected format. It is recommended the user inspect historyAction and historyQCTest.
```

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

In summary, I do believe more work is needed to fully understand `historyAction` and `historyQCTest`. Right now `showQCTests()` works only if tests performed and tests failed are listed once, otherwise it produces a warning message. I updated documentation to state this.

**Comment by j-harbin** [comment] 2021-11-04 14:07
Update: in commit 199e668744900602b9a5db3bca9f3d3a1b7fff46  of develop, I made the warning message more informative. See below

``` r
library(argoFloats)
ai <- getIndex()
index1 <- subset(ai, ID="6900388")
#> Kept 223 cycles (0.00879%)
profiles <- getProfiles(index1)
argos <- readProfiles(profiles)
#> Warning in readProfiles(profiles): Of 223 profiles read, 1 has >10% of pressure values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     14
showQCTests(argos[[1]])
#> Warning: historyAction is not in the expected format. The tests performed were recorded 2 times and the tests failed were recorded 0 times.
```

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by j-harbin** [comment] 2022-01-31 15:43
@dankelley,

Curious if you run the code in the above comment do you get the "Warning: historyAction is not in the expected format. The tests performed were recorded 2 times and the tests failed were recorded 0 times"

I know this only works in the develop branch of argoFloats (and not the CRAN version) but I tried 

```R
library(devtools)
remove.packages("argoFloats")
install_github("ArgoCanada/argoFloats", ref="develop")
library(argoFloats)
```

And then ran the above code, but I am still receiving the error from before (ie. "Error in rep("0", nchar(perf) - nchar(fail)): invalid 'times' argument"

**Comment by dankelley** [comment] 2022-01-31 15:50
Hm, that warning doesn't seem to be a warning.  Or, at least, when I do
```R
options(warn=3)
showQCTests(argos[[1]])
```
it doesn't get converted to an error.  I think if we are writing messages (as opposed to warnings) we ought to reword them so a user doesn't think they came from `warning()`.  That's because users like me do the `options()` trick whenever they see a warning,  so they can then do `traceback()` to see where the problem is.

**Comment by dankelley** [comment] 2022-01-31 15:56
So, yes, I get the same error.  I find the wording of our "warning" to be quite confusing, to be honest.  I think

1. we ought to issue an actual `warning()`, not a `message()`.
2. we ought to rewrite it a bit so it's clearer what 'tests failed were recorded' means.  Maybe, since this is for argo people, we ought to say that the number of `QCP$` items (performed) does not equal the number of `QCF$` items (failed).  Or something like that.  Maybe the wording is ok and I'm just distracted by something else.

My advice on debuging: put a temporary `browser()` line just after the `message()`.  Then you can print `tests` and so forth, to see what's up.  I'd also advise using `ncdump` at the unix commandline, to see the full contents of the netcdf file.

Let me know if you want to Z on this.

**Comment by dankelley** [comment] 2022-01-31 15:59
When I do
```
ncdump /Users/kelley/Dropbox/data/argo/D6900388_001.nc | less
```
at the commandline, I see
```
HISTORY_ACTION =
  "QCP$",
  "QCP$",
  "IP  ",
  "IP  " ;
```
which might be a clue.  (Perhaps "IP" means "in progress".  Or maybe "impressive puppy".)

**Comment by j-harbin** [comment] 2022-02-02 19:02
Just checked this on my end as well, and I can confirm that it all works. Thanks for this, Dan!

**Comment by dankelley** [comment] 2022-02-02 19:02
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Closed** 2022-02-02 19:57 UTC
Labels: bug
