### ISSUE TITLE
argoFloats Vignette

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#29] opened 2020-03-11 16:40 UTC
I'm creating this issue as a place to have record of changes for the argoFloats Vignette. The Vignette can be found under JH_CR_DK_oce_argo/sandbox/jlh/05_argoVignette/05_ideas_for_paper.Rmd

The mentioned references have been put into the shared Zotero.

As always, feedback is appreciated.

**Comment by j-harbin** [comment] 2020-04-17 14:36
Hi Team,

I've made a commit of a draft for the vignette (4b9a334). Here are some problems I am facing as of now:

1. We mentioned using the rectangle subset to analyze the area of the section plot within the oce package, and then subset by time for +- 6 months from the time at which the section data was taken. The problem here, however, is the section data is from 1993, and the 'merge' data is only from 2005-2017. As of now, I've solely subsetted for a random year (2010), but this can easily be changed.
2., I like the table @dankelley created in the `?getIndex()` page, which demonstrates the File Name, Nickname, and Contents. I know it is written in R Markdown format, but for some reason it does not show up when I do a knitR. (From what I am reading online, I'm thinking this format is in LaTex?)
```-R
\tabular{lll}{
*File Name*                       \tab *Nickname*              \tab *Contents*\cr
`ar_greylist.txt`                 \tab -                       \tab Suspious or malfunctioning float sensors.\cr
`ar_index_global_meta.txt.gz`     \tab -                       \tab Metadata files of the argo GDAC ftp site.\cr
`ar_index_global_prof.txt.gz`     \tab `"argo"`                \tab Argo data.\cr
`ar_index_global_tech.txt.gz`     \tab -                       \tab All technical files of the argo GDAC ftp site.\cr
`ar_index_global_traj.txt.gz`     \tab -                       \tab All trajectory files of the argo GDAC ftp site.\cr
`argo_bio-profile_index.txt.gz`   \tab `"bgc"` or `"bgcargo"`  \tab Biogeochemical Argo data (without S or T).\cr
`argo_bio-traj_index.txt.gz`      \tab -                       \tab Bio-trajectory files of the argo GDAC ftp site.\cr
`argo_merge-profile_index.txt.gz` \tab `"merge"` or `"merged"` \tab Merged `"argo"` and `"bgc"` data.\cr
}
```
3. When I do a ' Run all' for my chunks of code within R markdown, everything works. However, when I do a knitR, it won't go past 
```
plot(indexMerged)
```
due to and error (screenshot below)

![verror](https://user-images.githubusercontent.com/58750538/79580550-8b184380-809f-11ea-957f-2892903db385.png)


We're getting there, Team! Thanks :)

**Comment by dankelley** [comment] 2020-04-17 14:41
First, we decided the time should be the year 2018, Jan 1 to Dec whatever.

Second, I'll take a look at the table and try to reproduce your error.

PS. I'm doing about one push to "develop" every 10 minutes.  The automated builds are not liking the new use of the `sp` package, and I'm trying to figure out why (since the `.travis.yml` seems pretty much the same).  It should not matter that I'm doing these pushes, because it's unlikely any other team member is editing the file.  It's just that you want to be sure to do a "git pull" before pushing ... as always :-)

**Comment by dankelley** [comment] 2020-04-17 15:03
As for the table, I don't know.  I find it hard to debug the plotting call because RStudio crashes whenever it finds an error (a "feature" on my machine, which is running a beta R on a beta OS).  One thing is that I don't know what R is doing when you click to "knit".  I think it's time to just move this file from where it is, to the proper place for a vignette, and to add about 3 magic lines that *make* it a vignette.  @j-harbin do you mind if I do that, in a new branch called "vignette"?  (It needs a new branch so problems with the vignette build don't break the whole package build.)

Anyway, it seems to make the plot, as shown below.  But, again, since this is a file and not a vignette, I don't know if that means anything.

**Important:* Q: have you updated both oce and ocedata from github?  We definitely need that.



<img width="706" alt="Screen Shot 2020-04-17 at 11 58 21 AM" src="https://user-images.githubusercontent.com/99469/79583032-f3b4ef80-80a2-11ea-8cf9-7496b9e41b85.png">

**Comment by j-harbin** [comment] 2020-04-17 15:25
That sounds good @dankelley ! I have updated both oce and ocedata from github. When I click the qreen triangle to run that chunk of code I have no problem, and receive the same plot as you have shown above. 

The problem is when I do knit. It doesn't seem to like that! Maybe when it is a problem vignette this problem could be solved.

**Comment by dankelley** [comment] 2020-04-17 16:23
I moved it to the vignette and got it working (mostly).  I propose, @j-harbin, that you work on that branch for a while, and merge it into "develop" at some later date.  (Be sure to do a `git merge --no-ff develop` from time to time, of course!)  A few notes

1. the site http://r-pkgs.had.co.nz/vignettes.html has hints on working with vignettes.  I don't think it is easy with RStudio, actually, and I propose you don't worry about how to get a vignette built into a package.  That can be done later.  (To this day, after maybe 5 or even 10 years of working on the oce vignette, I still don't know how to stitch it into a package. I don't care hugely, because CRAN builds up vignettes and puts them online, and I think people look there.)
2. I removed your section numbers because my setup does that automatically
3. In some spots you are using TTT (where T means backtick) but you really mean `TTT{r eval=FALSE}` and I fixed some of those.
4. The problem of plotting was that you had not done a `library(oce)` beforehand.  That was enclosed in TTT so it was not done.
5. If you still have a problem, please let me know.

To reiterate: I do *not* know how to make the vignette actually build into the package.  That would be a good thing for you to figure out in phase 2 of this project, but we certainly do not need that now.  Now's the time to get the vignette into reasonable shape, I think.

**Comment by j-harbin** [comment] 2020-04-17 17:26
Works like a charm, thanks Dan. 

I've added an abstract, fixed the `TTT{r eval=FALSE}`, and made a **temporary** fix for the table (ie. changed it into a .png file, while I figure out the r markdown coding). 

As for the section subset, when I do the following code, unfortunately after I subset with the rectangle, it doesn't have any points that are within 2018 either. For now I did 2017, but again can be easily changed.

```-R
data(section, package='oce')
summary(section[['latitude']]) # To determine min and max latitude
summary(section[['longitude']]) # To determine min and max longitude
# Subset by rectangle
ai <- getIndex(file='merge', destdir='~/data/argo')
lonRect <- c(-73, -8)
latRect <- c(35, 39)
air <- subset(ai, rectangle=list(longitude=lonRect, latitude=latRect))
# Subset the rectangle by time
from <- as.POSIXct("2017-01-01", tz="UTC")
to <- as.POSIXct("2017-12-31", tz="UTC")
aiTime <- subset(air, time=list(from=from, to=to))
#Plot this subset
latbe <- aiTime[['latitude']]
lonbe <- aiTime[['longitude']]
belat <- 37
belon <- -35
data(coastlineWorldFine, package="ocedata")
plot(coastlineWorldFine, clongitude=belon, clatitude=belat, col="pink", span=6000)
points(lonbe,latbe)
```

**Comment by dankelley** [comment] 2020-04-17 17:33
Oh, 2018 was just pulled out of a hat.  PS. 
```R
> median(section[['latitude']])
[1] 36.251
```
so you might want to show
```R
lat0 <- median(section[["latitude"]]) # ignore points near coasts
latRect <- lat0 + c(-1, 1)
```
or something.

Please state commit hash in comments like this, so if I do 'git pull' I'll know that I'm up to date.  I can take a look at the table now ... I forgot, to be honest!

**Comment by dankelley** [comment] 2020-04-17 17:39
On the table, maybe try like they say in https://cran.r-project.org/web/packages/roxygen2/vignettes/rd-formatting.html and ignore trying to put in a caption.  The text can just say "a table of BLAH is below"; we don't need a table number etc.

**Comment by dankelley** [comment] 2020-04-18 13:26
@j-harbin I looked into the magic used to build vignettes, and may have found the solution -- see the wiki "Developer Notes" entry, which *might* work.  But this is one of those cases where I think the fancy RStudio and devtools scheme is harder than the "old-fashioned" way.

That old-fashioned way is to type the following in unix:
```
R CMD BUILD --compact-vignettes="qpdf" argofloats
R CMD CHECK --run-donttest --as-cran argoFloats_0.1.1.tar.gz
R CMD INSTALL argoFloats_0.1.1.tar.gz
```
and I know that this works, because when I  then launch R, and type
```R
library(argoFloats)
browseVignettes("argoFloats")
```
I see the vignette.

NOTES
1. This scheme does *not* work if you try to include .png files from the  `vignettes` directory, but we can build those files from within the vignette, so I modified to do that.
2. In setting plot parameters, I had to look in https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf as I always do. You should bookmark that, or download it, because it's very useful.
3. I think all the plots should have the same fontsize, and that the size should be visually similar to the text in the vignette.  This involves using rmarkdown codes like I've done for the `plot(section)` diagram.
4. I think all the plots should have captions.
5. I think plot captions should be numbered.  There may be a way to do this automatically, but I suggest doing it manually, e.g. change `fig.cap="..."` to `fig.cap="**Figure 1. ...".  Of course, we have to update the numbers if figures get added/deleted/moved, but that's easy.
6. I had to change `DESCRIPTION` to get the vignette working. 
7. I had to change `.travis.yml` to get travisCI working, but that was for the polygon-subset mods, not for this.  (**Update** the build now fails.  I'll look into that, and add a comment when it's fixed, likely not until Sunday or Monday.)

Sorry for "barging in" on this issue, but I have some experience with vignettes, and I'm hoping the team will focus on the content of the vignette next week, without having to worry about the mechanics.

PS.

**Comment by dankelley** [comment] 2020-04-18 13:32
Oh, the build failed because the vignette is loading data (see below).  So what I need to do, I guess, is to alter `DESCRIPTION` or maybe `.travis.yml` to tell it *not* to try to build the vignette.  Or maybe I can tell `travis.yml` to create that directory.  I'll look into it.
```
Quitting from lines 185-186 (argoFloats.Rmd) 
Error: processing vignette 'argoFloats.Rmd' failed with diagnostics:
First, create a directory named '~/data/argo'
--- failed re-building â€˜argoFloats.Rmdâ€™
```

**Comment by dankelley** [comment] 2020-04-18 15:16
I fixed the remote-build problem, simply by using `eval=FALSE` on any block that created local files. We don't need them for the vignette, because the built-in datasets are sufficient.

It passes both travisCI and appveyor tests.

I've merged the "vignettes" into "develop", and then back again, to be sure that these remote-build changes were present in both.  (I didn't want us trying to merge "vignettes" into "develop", only to find a conflict in tricky configuration files.)

As compensation to co-developers, for bothering them with github messages over the weekend, I offer this link to a cartoon in The Guardion, which might appeal to fans of physics, felines, or knitting: https://www.theguardian.com/lifeandstyle/picture/2020/mar/21/berger-wyse-on-physics-cartoon

**Comment by j-harbin** [comment] 2020-04-20 12:06
Great work to the vignette @dankelley ! It's pretty neat to see it coming together.

One thing I will note is without having the local files created (ai), the circle subset function does not occur for Figure 3 as shown below 

![bermudaError](https://user-images.githubusercontent.com/58750538/79749756-213dab00-82e6-11ea-9c77-f057fbca9225.png)

**Comment by dankelley** [comment] 2020-04-20 12:10
Yes, we can only use a built-in example, so it will need to use `data(index)`.  I'd suggest using the circle that's in the `subset` example, i.e. near Abaca Island, not Bermuda.

**Comment by j-harbin** [comment] 2020-04-21 13:32
Hi Team,

I've created a draft of the vignette (commit # f88f484). Any feedback you may have is greatly appreciated.

**Comment by dankelley** [comment] 2020-04-21 13:38
FYI, it helps to state the branch name, too, so people can go to that branch and pull.  In this case, I happen to be able to guess the name is "vignette" :-)

**Comment by dankelley** [comment] 2020-04-24 17:28
@j-harbin since we now have a vignette, I think you ought to close this issue.  This is following the 'oce' tradition of
1. closing an issue when it -- as defined narrowly by its title -- has been addressed
2. leaving it to the issue creator to close the issue

Of course we might want to have more issues for things relating to the vignette, but they ought to be separate issues.  The idea is partly that the list of open issues is like a "to to" list.

**Closed** 2020-04-27 11:19 UTC
